apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-public
  labels:
    app: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-public
  rules:
    - host: tddc88-company1-ht24.kubernetes-public.it.liu.se
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
